// An object that know all the ALLOWED ACTION TYPES
// ~ contract or standard
const ActionTypes = {
  // Category
  CATEGORIES_ALL_REQ: "CATEGORIES_ALL_REQ",
  CATEGORIES_ALL_OK: "CATEGORIES_ALL_OK",
  CATEGORIES_ALL_X: "CATEGORIES_ALL_X",

  CATEGORY_ADD_REQ: "CATEGORY_ADD_REQ",
  CATEGORY_ADD_OK: "CATEGORY_ADD_OK",
  CATEGORY_ADD_X: "CATEGORY_ADD_X",

  CATEGORY_DEL_REQ: "CATEGORY_DEL_REQ",
  CATEGORY_DEL_OK: "CATEGORY_DEL_OK",
  CATEGORY_DEL_X: "CATEGORY_DEL_X",

  CATEGORY_EDIT_REQ: "CATEGORY_EDIT_REQ",
  CATEGORY_EDIT_OK: "CATEGORY_EDIT_OK",
  CATEGORY_EDIT_X: "CATEGORY_EDIT_X",

  CATEGORIES_SEARCH_REQ: "CATEGORIES_SEARCH_REQ",
  CATEGORIES_SEARCH_OK: "CATEGORIES_SEARCH_OK",
  CATEGORIES_SEARCH_X: "CATEGORIES_SEARCH_X",

  CATEGORIES_IS_SEARCH: "CATEGORIES_IS_SEARCH"
  //CATEGORY_RANDOMIZED_REQ:   'CATEGORY_RANDOMIZED_REQ',
  //CATEGORY_RANDOMIZED_OK:    'CATEGORY_RANDOMIZED_OK',
  //CATEGORY_RANDOMIZED_X:     'CATEGORY_RANDOMIZED_X',

  //CATEGORY_CURRENT_RESET:    'CATEGORY_CURRENT_RESET',
};

export default ActionTypes;
